### ISSUE TITLE
hlsdl error: cannot find module "hlsdownloader"

### ISSUE THREAD

**Issue by yannLYS** [nmrony/hlsdownloader-cli#5] opened 2018-11-28 17:41 UTC
Hi,
I tried hlsdownloader-cli but get errors.

Command is : hlsdl http://url .m3u8 (link to m3u8 is valide, i can read the playlist)

I receive error :
module.js:549
    throw err;
    ^

Error: Cannot find module 'hlsdownloader'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/hlsdownloader-cli/bin/lib.js:1:542)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

I tried to fix, by reinstalling node_modules, hlsdownloader is installet too, I asked on forums, I updates npm... OS : ubuntu 18 (i tried on Mac OS idem).

Can you help ?

Thks, Yan

**Comment by nmrony** [comment] 2018-12-29 00:31
@yannLYS Thanks a lot for opening the issue. Extremely sorry for late reply. The problem is not with `hlsdl`.  It is in `hlsdownloader`. please run  the following commands. Hope this will resolve the issue.
```sh
# you may need to add sudo in front these command 
$ npm uninstall --global hlsdownloader-cli
$ npm cache clean --force
$ npm install --global hlsdownloader-cli
```

`hlsdownloader-cli` is still in active development. I will be grateful to you if you report issues or send feature request.  Feel free to reopen it if you face any issue related to this. Closing it for now.

**Closed by nmrony** 2018-12-29 00:31 UTC
Labels: bug
